### PR TITLE
fix(type-check): remove unnecessary passing of arg in useKeyboardActions

### PR DESCRIPTION
**Pull request by saw-jan**
## Description
command `pnpm check:style` is failing with:
```
packages/web-app-admin-settings/src/components/Groups/GroupsList.vue(260,43): error TS2554: Expected 0 arguments, but got 1.
packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue(458,43): error TS2554: Expected 0 arguments, but got 1.
packages/web-app-admin-settings/src/components/Users/UsersList.vue(307,43): error TS2554: Expected 0 arguments, but got 1.
 ELIFECYCLE  Command failed with exit code 2.
```
I have removed the unnecessary passing of arg in function `useKeyboardActions`. The change was introduced in https://github.com/owncloud/web/pull/9559

## Related Issue
- Fixes https://github.com/owncloud/web/issues/9569

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

### CODE REVIEW

**Review by JammingBen — APPROVED** [review]
Thanks for taking care!

**Review by JanAckermann — APPROVED** [review]
